// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class File1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void file1() {
    driver.get("https://www.saucedemo.com/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-credentials\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"login-password\"]")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("*[data-test=\"login-password\"]"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
    driver.findElement(By.id("react-burger-menu-btn")).click();
    driver.findElement(By.cssSelector("*[data-test=\"about-sidebar-link\"]")).click();
    js.executeScript("window.scrollTo(0,3124)");
    js.executeScript("window.scrollTo(0,4786)");
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(6) .MuiBox-root:nth-child(8) .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(6) .MuiBox-root:nth-child(8) .MuiTypography-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-outlined"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("mital@gmail.com");
    driver.findElement(By.id("FirstName")).click();
    driver.findElement(By.id("FirstName")).sendKeys("mital");
    driver.findElement(By.id("LastName")).sendKeys("baleja");
    driver.findElement(By.cssSelector(".mktoFormRow:nth-child(5) span")).click();
    driver.findElement(By.id("Company")).click();
    driver.findElement(By.id("Company")).sendKeys("abc");
    driver.findElement(By.id("Phone")).sendKeys("1234567891");
    driver.findElement(By.id("Country")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Country"));
      dropdown.findElement(By.xpath("//option[. = 'India']")).click();
    }
    driver.findElement(By.id("Solution_Interest__c")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Solution_Interest__c"));
      dropdown.findElement(By.xpath("//option[. = 'Mobile Application Testing']")).click();
    }
    driver.findElement(By.id("Sales_Contact_Comments__c")).click();
    driver.findElement(By.id("Sales_Contact_Comments__c")).sendKeys("hello");
    driver.findElement(By.id("LblmktoCheckbox_46362_0")).click();
    driver.findElement(By.cssSelector(".mktoButton")).click();
    driver.findElement(By.cssSelector(".mktoButton")).click();
  }
}
